### ISSUE TITLE
 String was not recognized as a valid TimeSpan.

### ISSUE THREAD

**Issue by SmartManoj** [pishangujeniya/clipsync-windows#1]
**To Reproduce**
1. Copy

**Desktop (please complete the following information):**
 - OS: [Windows] --> Supports any other
 - Version [10]

**Additional context**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: String was not recognized as a valid TimeSpan.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName)
   at System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.ProcessTerminalState(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(String input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.Parse(String input, IFormatProvider formatProvider)
   at ClipSync.ClipSyncControlForm.WndProc(Message& m) in C:\Users\Pishang\Documents\GitHub\clipsync-windows\WindowsFormApplication\ClipSyncWindowsFormApplication\ClipSyncController.cs:line 267
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by SmartManoj** [comment]
C:\Users\Pishang\Documents\GitHub\clipsync-windows\WindowsFormApplication\ClipSyncWindowsFormApplication\ClipSyncController.cs:line 267
 
How it shows your path?
Is it running on your server?

**Comment by pishangujeniya** [comment]
@SmartManoj  No, It is a local server system, so your PC will be acting as a server and also your PC act as a client,

- Totally far away from the Internet.
- No need of Internet.

> May be the code written so the path will be showing as the error in the code occured.

**Comment by pishangujeniya** [comment]
@SmartManoj  I am working a fix for it.
Thank you for creating an issue on it.
👍🏼

**Comment by pishangujeniya** [comment]
@SmartManoj  I have updated and released a new latest version with the fix.
https://github.com/pishangujeniya/clipsync-windows/releases/tag/v3.5.1.0
